# Generated by Django 3.0.7 on 2020-07-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200707_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ordered',
            new_name='closed',
        ),
    ]
